//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UKServiceProviderRecruiter
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CandidateInvoice()
        {
            this.CandidateContractInvoices = new HashSet<CandidateContractInvoice>();
        }
    
        public int InvoiceID { get; set; }
        public Nullable<int> InvoiceNum { get; set; }
        public Nullable<int> CandidateID { get; set; }
        public Nullable<int> HotelID { get; set; }
        public Nullable<int> CCID { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<int> HotelRequestID { get; set; }
        public string Summary { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateContractInvoice> CandidateContractInvoices { get; set; }
        public virtual Candidate Candidate { get; set; }
        public virtual HotelRequest HotelRequest { get; set; }
        public virtual Hotel Hotel { get; set; }
    }
}
