//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UKServiceProviderRecruiter
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateContract
    {
        public int CandidateContractID { get; set; }
        public Nullable<int> CCID { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public Nullable<System.DateTime> StatementDate { get; set; }
    
        public virtual CandidateContractInvoice CandidateContractInvoice { get; set; }
    }
}
