//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UKServiceProviderRecruiter
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateContractInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CandidateContractInvoice()
        {
            this.CandidateContracts = new HashSet<CandidateContract>();
        }
    
        public int CCID { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public Nullable<int> CandidateContractID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateContract> CandidateContracts { get; set; }
        public virtual CandidateInvoice CandidateInvoice { get; set; }
    }
}
