//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UKServiceProviderRecruiter
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HotelRequest()
        {
            this.HotelInvoices = new HashSet<HotelInvoice>();
            this.HotelRequestCandidates = new HashSet<HotelRequestCandidate>();
            this.CandidateInvoices = new HashSet<CandidateInvoice>();
        }
    
        public int HotelRequestID { get; set; }
        public Nullable<int> HotelID { get; set; }
        public Nullable<int> NumberOfCandidates { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string HoursNeeded { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public string Speciality { get; set; }
        public Nullable<int> StatusID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelInvoice> HotelInvoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelRequestCandidate> HotelRequestCandidates { get; set; }
        public virtual Hotel Hotel { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateInvoice> CandidateInvoices { get; set; }
    }
}
