//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UKServiceProviderRecruiter
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelContractInvoice
    {
        public int HotelContractInvoiceID { get; set; }
        public Nullable<int> HotelContractID { get; set; }
        public Nullable<int> InvoiceID { get; set; }
    
        public virtual HotelContract HotelContract { get; set; }
        public virtual HotelInvoice HotelInvoice { get; set; }
    }
}
