//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UKServiceProviderRecruiter
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelContract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HotelContract()
        {
            this.HotelContractInvoices = new HashSet<HotelContractInvoice>();
        }
    
        public int HotelContractID { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public Nullable<System.DateTime> StatementDate { get; set; }
    
        public virtual HotelInvoice HotelInvoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelContractInvoice> HotelContractInvoices { get; set; }
    }
}
