//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UKServiceProviderRecruiter
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HotelInvoice()
        {
            this.HotelContracts = new HashSet<HotelContract>();
            this.HotelContractInvoices = new HashSet<HotelContractInvoice>();
        }
    
        public int InvoiceID { get; set; }
        public Nullable<int> HotelID { get; set; }
        public Nullable<int> CandidateID { get; set; }
        public Nullable<int> HotelRequestID { get; set; }
        public Nullable<int> InvoiceNumber { get; set; }
        public string SummaryDescription { get; set; }
        public Nullable<System.DateTime> DateOfInvoice { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public string PaymentMethod { get; set; }
    
        public virtual Candidate Candidate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelContract> HotelContracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelContractInvoice> HotelContractInvoices { get; set; }
        public virtual HotelRequest HotelRequest { get; set; }
        public virtual Hotel Hotel { get; set; }
    }
}
