//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UKServiceProviderRecruiter
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelRequestCandidate
    {
        public int HotelRequestCandidateID { get; set; }
        public Nullable<int> hotelRequestID { get; set; }
        public Nullable<int> CandidateID { get; set; }
    
        public virtual Candidate Candidate { get; set; }
        public virtual HotelRequest HotelRequest { get; set; }
    }
}
