//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UKServiceProviderRecruiter
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SPRdbEntities : DbContext
    {
        public SPRdbEntities()
            : base("name=SPRdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Candidate> Candidates { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<HotelContract> HotelContracts { get; set; }
        public virtual DbSet<HotelContractInvoice> HotelContractInvoices { get; set; }
        public virtual DbSet<HotelInvoice> HotelInvoices { get; set; }
        public virtual DbSet<HotelRequestCandidate> HotelRequestCandidates { get; set; }
        public virtual DbSet<HotelRequest> HotelRequests { get; set; }
        public virtual DbSet<Hotel> Hotels { get; set; }
        public virtual DbSet<Status> Statuses { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<CandidateContract> CandidateContracts { get; set; }
        public virtual DbSet<CandidateContractInvoice> CandidateContractInvoices { get; set; }
        public virtual DbSet<CandidateInvoice> CandidateInvoices { get; set; }
    }
}
